// Diary
export const MEAL_UPDATED = 'MEAL_UPDATED';
export const MEAL_DELETED = 'MEAL_DELETED';
export const MEAL_PRODUCT_ADDED = 'MEAL_PRODUCT_ADDED';
export const MEALS_LOADED = 'MEALS_LOADED';
/** @deprecated */
export const MEAL_ADDED = 'MEAL_ADDED';
export const MEAL_PRODUCT_UPDATED = 'MEAL_PRODUCT_UPDATED';
export const MEAL_PRODUCT_DELETED = 'MEAL_PRODUCT_DELETED';
export const MEAL_TOGGLED = 'MEAL_TOGGLED';
export const PRODUCT_UPDATED = 'PRODUCT_UPDATED';
export const PRODUCT_TOGGLED = 'PRODUCT_TOGGLED';
export const PRODUCTS_RECENT_LOADED = 'PRODUCTS_RECENT_LOADED';

// Application
export const APP_DATE_UPDATED = 'APP_DATE_UPDATED';
export const APP_CONNECTION_STATUS_UPDATED = 'APP_CONNECTION_STATUS_UPDATED';
export const APP_INITIALIZED = 'APP_INITIALIZED';

// User
export const USER_PROFILE_CREATED = 'USER_PROFILE_CREATED';