export const REQUEST_FAILED = 'REQUEST_FAILED';

export const ADD_EXERCISE_SET = 'ADD_EXERCISE_SET';
export const UPDATE_EXERCISE_SET = 'UPDATE_EXERCISE_SET';
export const DELETE_EXERCISE_SET = 'DELETE_EXERCISE_SET';

/* Training */

export const UPDATE_TRAINING = 'UPDATE_TRAINING';

export const ADD_TRAINING_ASYNC = 'ADD_TRAINING_ASYNC';
export const ADD_TRAININGS = 'ADD_TRAININGS';


/* Training Exercises */

export const ADD_EXERCISE = 'ADD_EXERCISE';
export const UPDATE_EXERCISE = 'UPDATE_EXERCISE';
export const DELETE_EXERCISE = 'DELETE_EXERCISE';


export const ADD_EXERCISE_ASYNC = 'ADD_EXERCISE_ASYNC';
export const ADD_EXERCISE_SET_ASYNC = 'ADD_EXERCISE_SET_ASYNC';
export const UPDATE_EXERCISE_SET_ASYNC = 'UPDATE_EXERCISE_SET_ASYNC';
export const DELETE_EXERCISE_SET_ASYNC = 'DELETE_EXERCISE_SET_ASYNC';

export const DELETE_EXERCISE_ASYNC = 'DELETE_EXERCISE_ASYNC';


export const DELETE_TRAINING = 'DELETE_TRAINING';
export const DELETE_TRAINING_ASYNC = 'DELETE_TRAINING_ASYNC';



/*** DIARY ***/

/* Meals */

export const MEAL_CREATED = 'MEAL_CREATED';
export const MEAL_UPDATED = 'MEAL_UPDATED';
export const MEAL_DELETED = 'MEAL_DELETED';

export const MEAL_PRODUCT_CREATED = 'MEAL_PRODUCT_CREATED';
export const MEAL_PRODUCT_UPDATED = 'MEAL_PRODUCT_UPDATED'; // just use getState in dispatch to update meal's kcals ()
export const MEAL_PRODUCT_DELETED = 'MEAL_PRODUCT_DELETED';
export const PRODUCT_UPDATED = 'PRODUCT_UPDATED';

/*** MEASUREMENTS ***/

export const UPDATE_WEIGHT = 'UPDATE_WEIGHT';
export const UPDATE_WEIGHT_ASYNC = 'UPDATE_WEIGHT_ASYNC';
export const UPDATE_MEASUREMENT = 'UPDATE_MEASUREMENT';
export const UPDATE_MEASUREMENT_ASYNC = 'UPDATE_MEASUREMENT_ASYNC';
export const UPDATE_WEIGHT_GOAL = 'UPDATE_WEIGHT_GOAL';



/*** APPLICATION ***/

export const UPDATE_DATE = 'UPDATE_DATE';
export const UPDATE_LOGIN = 'UPDATE_LOGIN';
export const LOG_IN = 'LOG_IN';
export const LOG_OUT = 'LOG_OUT';
export const TEST_ACTION = 'TEST_ACTION';


/*** USER ***/
export const UPDATE_USER = 'UPDATE_USER';



/*** ACTIVE TRAINING ***/
export const START_TRAINING = 'START_TRAINING';
export const PAUSE_TRAINING = 'PAUSE_TRAINING';
export const FINISH_TRAINING = 'FINISH_TRAINING';
export const UPDATE_ACTIVE_TRAINING = 'UPDATE_TRAINING';
export const RESET_ACTIVE_TRAINING = 'RESET_TRAINING';
export const UPDATE_TRAINING_COUNTER = 'UPDATE_TRAINING_COUNTER';
export const ACTIVATE_SET_BREAK = 'ACTIVATE_SET_BREAK';
export const UPDATE_ACTIVE_SET = 'UPDATE_ACTIVE_SET';
export const EXTEND_SET_BREAK_DURATION = 'EXTEND_SET_BREAK_DURATION';


/*** REQUEST HANDLER  ***/
export const QUEUE_REQUEST = 'QUEUE_REQUEST';
export const POSTPONE_REQUEST = 'POSTPONE_REQUEST';