export const MEAL_CREATED = 'MEAL_CREATED';
export const MEAL_UPDATED = 'MEAL_UPDATED';
export const MEAL_DELETED = 'MEAL_DELETED';
export const MEAL_PRODUCT_ADDED = 'MEAL_PRODUCT_ADDED';
export const MEALS_ADDED = 'MEALS_ADDED';
// use getState in dispatch to update meal's kcals ?
export const MEAL_PRODUCT_UPDATED = 'MEAL_PRODUCT_UPDATED';
export const MEAL_PRODUCT_DELETED = 'MEAL_PRODUCT_DELETED';
export const MEAL_TOGGLED = 'MEAL_TOGGLED';
export const MEAL_TEMPLATE_TOGGLED = 'MEAL_TEMPLATE_TOGGLED';

export const PRODUCT_UPDATED = 'PRODUCT_UPDATED';
export const PRODUCT_CREATED = 'PRODUCT_CREATED';
export const PRODUCT_TOGGLED = 'PRODUCT_TOGGLED';

// Application
export const APP_DATE_UPDATED = 'APP_DATE_UPDATED';
export const APP_CONNECTION_STATUS_UPDATED = 'APP_CONNECTION_STATUS_UPDATED';
export const APP_INITIALIZED = 'APP_INITIALIZED';

// User
export const USER_PROFILE_CREATED = 'USER_PROFILE_CREATED';