name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Run npm install
      run: |
        npm i --silent
        npx jetify

    - name: Build with Gradle
      run: |
        cd android
        echo $RELEASE_KEYSTORE_BASE64 | base64 -d > ./app/release-key.keystore
        chmod +x ./gradlew
        ./gradlew assembleStaging

    - name: Rename built apk
      run: |
        cd ./android/app/build/outputs/apk/staging
        mv app-staging.apk app-${GITHUB_REF}.apk

    - uses: actions/upload-artifact@master
      with:
        name: ediary-staging-${GITHUB_REF}
        path: ./android/app/build/outputs/apk/staging/app-${GITHUB_REF}.apk